export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOAD_EVENTS_BEGIN = 'LOAD_EVENTS_BEGIN';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';

export const LOAD_RESOURCES_BEGIN = 'LOAD_RESOURCES_BEGIN';
export const LOAD_RESOURCES_SUCCESS = 'LOAD_RESOURCES_SUCCESS';

export const LOAD_CURRENT_SHIFT = 'LOAD_CURRENT_SHIFT';
export const LOAD_CURRENT_SHIFT_BEGIN = 'LOAD_CURRENT_SHIFT_BEGIN';
export const LOAD_CURRENT_SHIFT_SUCCESS = 'LOAD_CURRENT_SHIFT_SUCCESS';
export const CLEAR_CURRENT_SHIFT = 'CLEAR_CURRENT_SHIFT';
